Fix dependency error
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
lightning 2.0.2 requires fastapi<0.89.0,>=0.69.0, but you have fastapi 0.100.0 which is incompatible.
so-vits-svc-fork 3.14.1 requires fastapi==0.88, but you have fastapi 0.100.0 which is incompatible.